[program:local-ai-embedding]
environment=PROC_NAME="%(program_name)s"
command=/opt/supervisor-scripts/local-ai-embedding.sh
priority=10
autostart=true
autorestart=true
exitcodes=0
startsecs=0
stopasgroup=true
killasgroup=true
stopsignal=TERM
stopwaitsecs=120
stdout_logfile=/dev/stdout
redirect_stderr=true
stdout_events_enabled=true
stdout_logfile_maxbytes=0
stdout_logfile_backups=0
